### ISSUE TITLE
Error parsing CMP dats, with dats produced by ST, and minor error in commandline parser

### ISSUE THREAD

**Issue by bleuge** [SabreTools/SabreTools#30]
>SabreTools v1.0.3-2020-09-28 05:16:03

A minor thing, but maybe this could produce side effects, 
>sabretools -h - 
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at SabreTools.Library.Help.Help.OutputIndividualFeature(String featurename, Boolean includeLongDescription) in C:\projects\sabretools\SabreTools.Library\Help\Help.cs:line 201
   at SabreTools.Features.DisplayHelp.ProcessArgs(String[] args, Help help) in C:\projects\sabretools\SabreTools\Features\DisplayHelp.cs:line 26
   at SabreTools.Program.Main(String[] args) in C:\projects\sabretools\SabreTools\Program.cs:line 83

Dat parsing error
I got last mame xml file (225), converted it to CMP with
>sabretools -ud -ot=cmp mamefile.xml

Then ask for stats in the produced file,
>sabretools -st mamefile.dat

And got many of these:
ERROR 'K:\0\00main\datroot\mame\mame0225.dat' - There was an error parsing line 557051 'biosset ( name "4ms" description "Customize 3.5" 4ms" )': System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SabreTools.Library.IO.ClrMameProReader.ProcessLine() in C:\projects\sabretools\SabreTools.Library\IO\ClrMameProReader.cs:line 222
   at SabreTools.Library.IO.ClrMameProReader.ReadNextLine() in C:\projects\sabretools\SabreTools.Library\IO\ClrMameProReader.cs:line 107
   at SabreTools.Library.DatFiles.ClrMamePro.ReadSet(ClrMameProReader cmpr, Boolean resource, String filename, Int32 indexId) in C:\projects\sabretools\SabreTools.Library\DatFiles\ClrMamePro.cs:line 232
   at SabreTools.Library.DatFiles.ClrMamePro.ParseFile(String filename, Int32 indexId, Boolean keep, Boolean throwOnError) in C:\projects\sabretools\SabreTools.Library\DatFiles\ClrMamePro.cs:line 78
ERROR 'K:\0\00main\datroot\mame\mame0225.dat' - There was an error parsing line 557052 'biosset ( name "12ms" description "Customize 3.5" 12ms" )': System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SabreTools.Library.IO.ClrMameProReader.ProcessLine() in C:\projects\sabretools\SabreTools.Library\IO\ClrMameProReader.cs:line 222
   at SabreTools.Library.IO.ClrMameProReader.ReadNextLine() in C:\projects\sabretools\SabreTools.Library\IO\ClrMameProReader.cs:line 107
   at SabreTools.Library.DatFiles.ClrMamePro.ParseFile(String filename, Int32 indexId, Boolean keep, Boolean throwOnError) in C:\projects\sabretools\SabreTools.Library\DatFiles\ClrMamePro.cs:line 59

**Comment by mnadareski** [comment]
I usually prefer separate errors treated separately, but hey. The second one is actually really easy to fix since descriptions in CMP shouldn't contain a quote mark. That's pretty simple.

**Comment by mnadareski** [comment]
The help thing should be handled as of https://github.com/SabreTools/SabreTools/commit/2099a82b2b2f4be05d9a81b2840ec0ecea1e8f1c
