### ISSUE TITLE
Can't create dat file if .zip files are non-standard

### ISSUE THREAD

**Issue by ReignStumble** [SabreTools/SabreTools#41]
I'm currently trying sabertool in order to create a dat from a folder, it seems pretty straightfoward, I use:
.\SabreTools.exe -d 'Z:\Tools\NKit_v1.4\Processed\Wii RVZ'
But I get errors on all files
ERROR System.Exception: Unknown
   at SabreTools.FileTypes.Archives.ZipArchive.GetChildren() in B:\Programs\GitHub\SabreTools\SabreTools.FileTypes\Archives\ZipArchive.cs:line 281
5.44%: Z:\Tools\NKit_v1.4\Processed\Wii RVZ\Disney Alice in Wonderland (Europe) (En,Fr,De,Es,It,Nl).zip
ERROR System.Exception: Unknown
   at SabreTools.FileTypes.Archives.ZipArchive.GetChildren() in B:\Programs\GitHub\SabreTools\SabreTools.FileTypes\Archives\ZipArchive.cs:line 281
5.46%: Z:\Tools\NKit_v1.4\Processed\Wii RVZ\Chocobo no Fushigi na Dungeon - Toki-wasure no Meikyuu (Japan).zip
ERROR System.Exception: Unknown
   at SabreTools.FileTypes.Archives.ZipArchive.GetChildren() in B:\Programs\GitHub\SabreTools\SabreTools.FileTypes\Archives\ZipArchive.cs:line 281
5.50%: Z:\Tools\NKit_v1.4\Processed\Wii RVZ\Bratz - Girlz Really Rock (Europe) (En,Sv).zip
ERROR System.Exception: Unknown
   at SabreTools.FileTypes.Archives.ZipArchive.GetChildren() in B:\Programs\GitHub\SabreTools\SabreTools.FileTypes\Archives\ZipArchive.cs:line 281
5.54%: Z:\Tools\NKit_v1.4\Processed\Wii RVZ\Bratz - Girlz Really Rock (Scandinavia) (No,Da).zip
ERROR System.Exception: Unknown
   at SabreTools.FileTypes.Archives.ZipArchive.GetChildren() in B:\Programs\GitHub\SabreTools\SabreTools.FileTypes\Archives\ZipArchive.cs:line 281
5.59%: Z:\Tools\NKit_v1.4\Processed\Wii RVZ\Bratz - Girlz Really Rock (Europe) (De,Es,It).zip
ERROR System.Exception: Unknown
   at SabreTools.FileTypes.Archives.ZipArchive.GetChildren() in B:\Programs\GitHub\SabreTools\SabreTools.FileTypes\Archives\ZipArchive.cs:line 281
The zip files are torrentzip created with romvault tool

I'm using a modified version (TrrntZipUI 2.5.3 special (ISO)) that Gordon created for a guy to be able to drag and drop .iso in TrrntZip

I've modified in hex editor the .ISO to .RVZ

**Comment by mnadareski** [comment]
This ended up being fixed by an external patch
